##### test data _ NOT RUN in Local #####
library(data.table)
library(lubridate)
library(dplyr)
adte <- fread("../input/test.csv")
adte <- adte %>% select(-click_id)
adte$click_hour <- hour(adte$click_time)
adte$click_weekd <- wday(adte$click_time)
adte <- adte %>% add_count(ip, click_hour, click_weekd) 
adte <- adte %>% add_count(ip, app)
adte <- adte %>% add_count(ip, device)
adte <- adte %>% add_count(ip, os)
adte <- adte %>% add_count(ip, channel)
adte <- adte %>% add_count(ip)
adte <- adte %>% add_count(app)
adte <- adte %>% add_count(device)
adte <- adte %>% add_count(os)
adte <- adte %>% add_count(channel)
head(adte)
colnames(adte)[9:18] <- c("ip_hw", "ip_app", "ip_dev", "ip_os", "ip_ch", 
                          "ip_cnt", "app_cnt", "dev_cnt", "os_cnt", "ch_cnt")
adte <- adte %>% select(-ip, -click_time)
saveRDS(adte, "adte.RDS")
list.files()
rm(list=ls()); gc()

adte <- readRDS("adte.RDS")
