rm(list=ls()); gc()
library(data.table)
adt <- fread("../input/train_sample.csv")
library(lubridate)
colnames(adt)
adt$click_time <- as.POSIXct(adt$click_time)
adt$attributed_time <- ifelse(adt$is_attributed ==0, "2017-11-06 00:00:00",
                              adt$attributed_time)
adt$attributed_time <- as.POSIXct(adt$attributed_time)
head(adt)
head(adt[adt$is_attributed ==1 , ])
adt$down_time <- adt$attributed_time - adt$click_time
str(adt$down_time)
adt$click_hour <- hour(adt$click_time)
adt$click_weekd <- wday(adt$click_time)
adt$down_time <- as.integer(adt$down_time)
range(adt$down_time)
table(adt$down_time)
#46341 4521608
adt$down_time <- ifelse(adt$down_time < 0, 0, adt$down_time)
colnames(adt)
library(dplyr)
colnames(adt)
adt <- adt %>% add_count(ip, click_hour, click_weekd)
adt <- adt %>% add_count(ip, app)
adt <- adt %>% add_count(ip, device)
adt <- adt %>% add_count(ip, os)
adt <- adt %>% add_count(ip, channel)
adt <- adt %>% add_count(ip)
adt <- adt %>% add_count(app)
adt <- adt %>% add_count(device)
adt <- adt %>% add_count(os)
adt <- adt %>% add_count(channel)
head(adt)
colnames(adt)[12:21] <- c("ip_hw", "ip_app", "ip_dev", "ip_os", "ip_ch", 
                          "ip_cnt", "app_cnt", "dev_cnt", "os_cnt", "ch_cnt")
colnames(adt)
#te_hourG1 <- c(4, 14, 13, 10, 9, 5)
#te_hourG2 <- c(15, 11, 6)
#adt$h_div <- ifelse(adt$click_hour %in% te_hourG1, 1, 
#                    ifelse(adt$click_hour %in% te_hourG2, 3, 2))
adt <- adt %>% add_count(ip, device, os)
adt <- adt %>% add_count(ip, device, os, app)
colnames(adt)[22:23] <- c("clicker", "clicker_app")

adt <- adt %>% group_by(ip, device, os) %>% mutate(clicker_N = 1:n())
adt <- adt %>% group_by(ip, device, os, app) %>% mutate(clicker_app_N = 1:n())
colnames(adt)
#head(adt[, 19:24])  