glimpse(bike)
model.matrix(~. -1, bike)
bike <- cbind(bike, model.matrix(~. -1, bike))
head(bike)
range(bike$windspeed)
colnames(bike)
bike$season      <- factor(bike$season)
bike$holiday     <- factor(bike$holiday)
bike$workingday  <- factor(bike$workingday)
bike$weather    <- factor(bike$weather)
bike$year       <- factor(bike$year)
bike$month       <- factor(bike$month)
bike$yday       <- factor(bike$yday)
bike$mday       <- factor(bike$mday)
bike$wday       <- factor(bike$wday)
bike$qday       <- factor(bike$qday)
bike$week        <- factor(bike$week)
bike$hour        <- factor(bike$hour)  
bike$am          <- factor(bike$am)    
bike$pm          <- factor(bike$pm) 
bike$h_dvi       <- factor(bike$h_dvi)  
bike <- model.matrix(~. -1, bike)
bike <- sparse.model.matrix(~. -1, bike)
library(Matrix)
bike <- cbind(bike, sparse.model.matrix(~. -1, bike))
bike

# "temp"       "atemp"     "humidity"   "windspeed"
table(bike$temp)
table(bike$atemp)
table(bike$humidity)
table(bike$windspeed)
